name: Build files
on:
  push:
    branches:
      - maas-discourse

jobs:
  build:
    name: Builld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - name: Build files
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update the common folder content
          branch: maas-discourse
          file_pattern: common/*.*
