name: Build files
on:
  push:
    branches:
      - snapcraft-forum
      - ubuntu-discourse
      - maas-discourse
      - charmhub-discourse

jobs:
  build:
    name: Builld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${GITHUB_HEAD_REF}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - name: Build files
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update the common folder content - triggered by $GITHUB_ACTOR
          branch: $GITHUB_HEAD_REF
          file_pattern: common/*.*
