name: Build files
on:
  push:
    branches:
      - main
      - forum-snapcraft
      - ubuntu-discourse
      - maas-discourse
      - charmhub-discourse

jobs:
  build:
    name: Builld
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - name: Build files
        run: npm run build
